### ISSUE TITLE
Compile from source

### ISSUE THREAD

**Issue by raffaem** [ineshbose/simple-icons-latex#23]
Can you provide instructions on how to compile from source?

I'm affected by #18  and my distribution (Arch Linux) supply old version of this package (8.x)

**Comment by ineshbose** [comment]
There are a couple of things you can do...

The easiest is to download the latest release ZIP from https://github.com/ineshbose/simple-icons-latex/releases and use that. Otherwise, you clone the repository (and assuming you have Node.js installed), install dependencies (using npm/yarn), and then run `node bindings.js`.

**Comment by raffaem** [comment]
Thanks. I ended up using the SVG files directly. (maybe we can put those instructions in README)
